# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgSettings(object):
    def setupUi(self, dlgSettings):
        dlgSettings.setObjectName("dlgSettings")
        dlgSettings.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(9)
        dlgSettings.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("jack_cast_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgSettings.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgSettings)
        self.buttonBox.setGeometry(QtCore.QRect(0, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lblSettings = QtWidgets.QLabel(dlgSettings)
        self.lblSettings.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblSettings.setFont(font)
        self.lblSettings.setTextFormat(QtCore.Qt.AutoText)
        self.lblSettings.setObjectName("lblSettings")
        self.splitter = QtWidgets.QSplitter(dlgSettings)
        self.splitter.setGeometry(QtCore.QRect(80, 50, 261, 191))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.lblIP = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lblIP.setFont(font)
        self.lblIP.setTextFormat(QtCore.Qt.AutoText)
        self.lblIP.setObjectName("lblIP")
        self.txtIP = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtIP.setFont(font)
        self.txtIP.setReadOnly(False)
        self.txtIP.setObjectName("txtIP")
        self.lblMulticast = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lblMulticast.setFont(font)
        self.lblMulticast.setTextFormat(QtCore.Qt.AutoText)
        self.lblMulticast.setObjectName("lblMulticast")
        self.cmbMulticast = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbMulticast.setFont(font)
        self.cmbMulticast.setObjectName("cmbMulticast")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.cmbMulticast.addItem("")
        self.lblResolution = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lblResolution.setFont(font)
        self.lblResolution.setTextFormat(QtCore.Qt.AutoText)
        self.lblResolution.setObjectName("lblResolution")
        self.cmbResolution = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbResolution.setFont(font)
        self.cmbResolution.setObjectName("cmbResolution")
        self.cmbResolution.addItem("")
        self.cmbResolution.addItem("")
        self.cmbResolution.addItem("")

        self.retranslateUi(dlgSettings)
        self.buttonBox.accepted.connect(dlgSettings.accept)
        self.buttonBox.rejected.connect(dlgSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgSettings)

    def retranslateUi(self, dlgSettings):
        _translate = QtCore.QCoreApplication.translate
        dlgSettings.setWindowTitle(_translate("dlgSettings", "Jack Cast"))
        self.lblSettings.setText(_translate("dlgSettings", "Settings"))
        self.lblIP.setText(_translate("dlgSettings", "IP Address:"))
        self.txtIP.setText(_translate("dlgSettings", "127.0.0.1"))
        self.lblMulticast.setText(_translate("dlgSettings", "Multicast Group:"))
        self.cmbMulticast.setCurrentText(_translate("dlgSettings", "239.1.1.1"))
        self.cmbMulticast.setItemText(0, _translate("dlgSettings", "239.1.1.1"))
        self.cmbMulticast.setItemText(1, _translate("dlgSettings", "239.1.1.2"))
        self.cmbMulticast.setItemText(2, _translate("dlgSettings", "239.1.1.3"))
        self.cmbMulticast.setItemText(3, _translate("dlgSettings", "239.1.1.4"))
        self.cmbMulticast.setItemText(4, _translate("dlgSettings", "239.1.1.5"))
        self.cmbMulticast.setItemText(5, _translate("dlgSettings", "239.1.1.6"))
        self.cmbMulticast.setItemText(6, _translate("dlgSettings", "239.1.1.7"))
        self.cmbMulticast.setItemText(7, _translate("dlgSettings", "239.1.1.8"))
        self.cmbMulticast.setItemText(8, _translate("dlgSettings", "239.1.1.9"))
        self.lblResolution.setText(_translate("dlgSettings", "Resolution:"))
        self.cmbResolution.setCurrentText(_translate("dlgSettings", "1920 x 1080"))
        self.cmbResolution.setItemText(0, _translate("dlgSettings", "1920 x 1080"))
        self.cmbResolution.setItemText(1, _translate("dlgSettings", "1366 x 768"))
        self.cmbResolution.setItemText(2, _translate("dlgSettings", "1280 x 720"))

